#! /bin/sh
sxhkd &
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

###---WINDOW-ASSIGNMENTS-&-RULES---###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a spotify desktop='^4'
bspc node 0x2800002 -d 4 
bspc rule -a steam desktop='^5' follow=no

###---AUTOSTART---###
feh --bg-scale ~/Pictures/Wallpapers/Wallpap4.jpg &
~/.config/polybar/classic2/launch.sh &
~/.config/scripts/external-rules.sh &
picom -b &
killall "firefox"
firefox &
killall "dunst"
dunst & 
killall "discord"
./~/.local/lib/Discord/Discord &
killall "spotify"
spotify &

###---Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod4
bpsc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true

##---Border-Colors---##
bspc config normal_border_color "#0a0d0f"
bspc config active_border_color "#0a0d0f"
bspc config focused_border_color "#0a0d0f"
bspc config urgent_border_color "#ff7575"

##--Gaps--##
bspc config top_padding 10
bspc config bottom_padding 10
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2 
bspc config windowgap 15
